function GF_Help(cmd)
	if cmd == "" or cmd == nil then
        GF_LargessMessage("","sys")
        GF_LargessMessage("--------------------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter v"..GF_VERSION,"sys")
        GF_LargessMessage("by Azinath-Lightninghoof","sys")
        GF_LargessMessage("--------------------------------------","sys")
		GF_LargessMessage("usage: /gbh <command> <args>","sys")
		GF_LargessMessage("Type '/gbh help <command>' for info on a specific gbh command.","sys")
		GF_LargessMessage("","sys")
		GF_LargessMessage("Available gbh commands:","sys")
		GF_LargessMessage("   audit","sys")
		GF_LargessMessage("   bounty","sys")
		GF_LargessMessage("   clear","sys")
		GF_LargessMessage("   cut","sys")
        GF_LargessMessage("   gbimport","sys")
		GF_LargessMessage("   intel","sys")
		GF_LargessMessage("   largess","sys")
		GF_LargessMessage("   list","sys")
        GF_LargessMessage("   onotes","sys")
        GF_LargessMessage("   pnotes","sys")
        GF_LargessMessage("   scale","sys")
		GF_LargessMessage("   sync","sys")
        GF_LargessMessage("   gbimport","sys")
        GF_LargessMessage("   setminrank","sys")
        GF_LargessMessage("   users","sys")
    elseif cmd == "audit" then
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter","sys")
        GF_LargessMessage("Audit","sys")
        GF_LargessMessage("-----------------------------","sys")
		GF_LargessMessage("usage: /gbh audit [bounties|list|clear]","sys")
		GF_LargessMessage("Reads the guild bank money log and bounty list and updates Largess officer notes for all new transactions.","sys")		
		GF_LargessMessage("Requires officer note and guild info write permissions.","sys")
		GF_LargessMessage("Requires a guild bank money log and guild roster refresh.","sys")
		GF_LargessMessage("The optional 'bounties' argument will only audit bounties.","sys")
		GF_LargessMessage("The optional 'list' argument will list all guild bank transactions THIS character has audited.","sys")
   		GF_LargessMessage("The optional 'clear' argument clears the audit history list for THIS character.","sys")    
	elseif cmd == "bounty" then
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter","sys")
        GF_LargessMessage("Bounty","sys")
        GF_LargessMessage("-----------------------------","sys")
		GF_LargessMessage("useage: /gbh bounty [<amount> | bg <amount>]","sys")
		GF_LargessMessage("Opens the add bounty dialog box populated with current target data.","sys")
		GF_LargessMessage("If an amount is included \(in copper\) then the dialog box will not open and a bounty will be placed on the current target for the specified amount.","sys")
		GF_LargessMessage("It may be useful to create a macro like self: /gbh bounty 10123","sys")
		GF_LargessMessage("This macro could be used to quickly add a bounty to your target for 1g 1s 23c","sys")
		GF_LargessMessage("The 'bg <amount>' option only works in a battleground.","sys")
		GF_LargessMessage("It adds a bounty for <amount> on every enemy player currently in the battleground.","sys")
		GF_LargessMessage("Using the 'bg' option may require a refresh of the BG Stats list.","sys")
	elseif cmd == "clear" then
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter","sys")
        GF_LargessMessage("Clear","sys")
        GF_LargessMessage("-----------------------------","sys")
		GF_LargessMessage("useage: /gbh clear [all]","sys")
		GF_LargessMessage("Clears your local bounty list.","sys")
		GF_LargessMessage("Using the 'all' option also the clears the bounty lists for all online guild members.","sys")
		GF_LargessMessage("The 'all' option requires officer note and guild info write permission.","sys")
	elseif cmd == "cut" then
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter","sys")
        GF_LargessMessage("Bank Cut","sys")
        GF_LargessMessage("-----------------------------","sys")
		GF_LargessMessage("useage: /gbh cut <0-1>","sys")
		GF_LargessMessage("Sets the guild bank %cut on all Largess deposits.","sys")
		GF_LargessMessage("Requires officer note and guild info write permission.","sys")
	elseif cmd == "intel" then
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter","sys")
        GF_LargessMessage("Intel","sys")
        GF_LargessMessage("-----------------------------","sys")
		GF_LargessMessage("useage: /gbh intel post | spy | report","sys")
		GF_LargessMessage("Gathers intelligence data on your bounty targets \(e.g. zone, class, level\)","sys")
		GF_LargessMessage("'post' will copy your bounty list to a variable accessible account wide.","sys")
		GF_LargessMessage("'spy' will call /who on all friendly players from the account wide list.","sys")
		GF_LargessMessage("'report' will copy the /who info from the account wide list to your character bounty list.","sys")
		GF_LargessMessage("Typical usage would be to call '/gbh intel post' from the character whos list you seek intel on.","sys")
		GF_LargessMessage("Then log onto a character of the opposite faction and call '/gbh intel spy'.","sys")
		GF_LargessMessage("Once the data has been gathered, log back on with the first character and call '/gbh intel report'.","sys")
	elseif cmd == "largess" then
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter","sys")
        GF_LargessMessage("Largess","sys")
        GF_LargessMessage("-----------------------------","sys")
		GF_LargessMessage("usage: /gbh largess [report | set <player> <amount> | mod <player> <amount>]","sys")
		GF_LargessMessage("When called with no arguments, it prints the player's current largess amount.","sys")
		GF_LargessMessage("Using the 'report' option will print the largess for all guild members.","sys")
		GF_LargessMessage("'report' requires officer note read permission.","sys")
		GF_LargessMessage("'set' sets <player> largess equal to <amount> \(in copper\).","sys")
		GF_LargessMessage("'set' requires officer note write permission.","sys")
		GF_LargessMessage("'mod' adds <amount> to <player> largess. <amount> can be negative or positive \(in copper\).","sys")
		GF_LargessMessage("'mod' requires officer note write permission. ","sys")
		GF_LargessMessage("Both 'set' and 'mod' accept <player='all'> to apply largess changes to all guild members.","sys")
	elseif cmd == "list" then
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter","sys")
        GF_LargessMessage("List","sys")
        GF_LargessMessage("-----------------------------","sys")
		GF_LargessMessage("usage: /gbh list","sys")
		GF_LargessMessage("Prints the filtered bounty list to selected channels.","sys")
    elseif cmd == "onotes" then
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter","sys")
        GF_LargessMessage("Officer Notes","sys")
        GF_LargessMessage("-----------------------------","sys")
		GF_LargessMessage("usage: /gbh onotes save <tag> | load <tag> | list","sys")
		GF_LargessMessage("save <tag> saves the guild officer notes with the name <tag>.","sys")
        GF_LargessMessage("load <tag> loads the guild officer notes saved with the name <tag>.","sys")
        GF_LargessMessage("list displays the tags of all the saved officer notes.","sys")
    elseif cmd == "pnotes" then
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter","sys")
        GF_LargessMessage("Public Notes","sys")
        GF_LargessMessage("-----------------------------","sys")
		GF_LargessMessage("usage: /gbh pnotes save <tag> | load <tag> | list","sys")
		GF_LargessMessage("save <tag> saves the guild public notes with the name <tag>.","sys")
        GF_LargessMessage("load <tag> loads the guild public notes saved with the name <tag>.","sys")
        GF_LargessMessage("list displays the tags of all the saved public notes.","sys")
	elseif cmd == "sync" then 
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter","sys")
        GF_LargessMessage("Sync","sys")
        GF_LargessMessage("-----------------------------","sys")
		GF_LargessMessage("usage: /gbh sync","sys")
		GF_LargessMessage("Forces a resynchronization of your bounty list with all online guild members.","sys")
		GF_LargessMessage("This is done automatically on entering the game world and on UI reload.","sys")
    
    elseif cmd == "gbimport" then
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter","sys")
        GF_LargessMessage("Guild Bank Import","sys")
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("usage: /gbh gbimport [<discount>]","sys")
        GF_LargessMessage("Imports all items in the currently selected guild bank tab into the GBH item list with prices from the Auctionator addon.","sys")
        GF_LargessMessage("If <discount> is provided, it will apply it to the Auctionator prices.","sys")
        
    elseif cmd == "setminrank" then
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter","sys")
        GF_LargessMessage("Set Minimum Officer Rank","sys")
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("usage: /gbh setminrank <rankindex>","sys")
        GF_LargessMessage("Sets the minimum officer rank for enforcing Officer Locked bounties.","sys")
        GF_LargessMessage("GBH will not accept any bounty updates from players who's rank index is greater than <rankindex>.","sys")
    elseif cmd == "scale" then
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter","sys")
        GF_LargessMessage("Set GBH UI Scale","sys")
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("usage: /gbh scale <scale>","sys")
        GF_LargessMessage("Sets the scale of the main Guild Bounty Hunter UI frame.","sys")
    elseif cmd == "users" then
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("Guild Bounty Hunter","sys")
        GF_LargessMessage("Lists Online Users","sys")
        GF_LargessMessage("-----------------------------","sys")
        GF_LargessMessage("usage: /gbh users","sys")
        GF_LargessMessage("Reports back a list of GBH users online and their version number.","sys")
	end
end
